apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:latest
        ports:
        - containerPort: 5000
        command: ["mlflow"]
        args: [
          "server",
          "--backend-store-uri", "sqlite:///mlflow/mlflow.db",
          "--default-artifact-root", "/mlflow/artifacts",
          "--host", "0.0.0.0",
          "--port", "5000",
          "--serve-artifacts"
        ]
        volumeMounts:
        - name: mlflow-artifacts
          mountPath: /mlflow/artifacts
        - name: mlflow-db
          mountPath: /mlflow
      volumes:
      - name: mlflow-artifacts
        emptyDir: {}
      - name: mlflow-db
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32000
